#print('Informe o seu nome')
#nome = str(input('Digite seu nome'))
#print(f'Bom dia {nome}')
#print('Informe o seu nome')
#nome = input()
#print('Nome: ', nome)
numero1 = int(input('Digite a primeira nota'))
numero2 = int(input('Digite a segunda nota'))
media = (numero1 + numero2) / 2
print(f'A media é {media}')